export const produtos = [
  {
    id: 1,
    nome: "Sabonete Artesanal",
    preco: "R$ 10,00",
    avaliacao: 4.5,
    foto: "../assets/produtos/sabonete.jpg",
    vendedor: "Maria",
    categoria: "Banho",
    vendas: 1,
    avaliacaoUsuario: "Produto muito bom! A fragrância é agradável e a qualidade do sabonete é ótima. Poderia ser um pouco maior, mas no geral, estou muito satisfeito.",
  },
  {
    id: 2,
    nome: "Panela de Barro",
    preco: "R$ 120,00",
    avaliacao: 4.8,
    foto: "../assets/produtos/panela.jpg",
    vendedor: "Amanda",
    categoria: "Cozinha",
    vendas: 1,
    avaliacaoUsuario: "Excelente panela! O calor é distribuído uniformemente, e os alimentos ficam com um sabor maravilhoso. Vale cada centavo.",
  },
  {
    id: 3,
    nome: "Toalha de Banho Bordada",
    preco: "R$ 45,00",
    avaliacao: 4.7,
    foto: "../assets/produtos/toalha.jpg",
    vendedor: "Ana",
    categoria: "Banho",
    vendas: 1,
    avaliacaoUsuario: "Toalha de alta qualidade, o bordado é muito bonito e o tecido é muito macio. Recomendo fortemente!",
  },
  {
    id: 4,
    nome: "Conjunto de Talheres",
    preco: "R$ 80,00",
    avaliacao: 4.6,
    foto: "../assets/produtos/talheres.jpg",
    vendedor: "Carla",
    categoria: "Cozinha",
    vendas: 1,
    avaliacaoUsuario: "Talheres de ótima qualidade, com acabamento impecável. Apenas um dos garfos tinha uma pequena imperfeição, mas nada grave.",
  },
  {
    id: 5,
    nome: "Vaso de Cerâmica",
    preco: "R$ 60,00",
    avaliacao: 4.5,
    foto: "../assets/produtos/vaso.jpg",
    vendedor: "Fernanda",
    categoria: "Jardim e Decoração",
    vendas: 1,
    avaliacaoUsuario: "Vaso muito bonito e bem acabado. O design é moderno e combina perfeitamente com a decoração da minha sala.",
  },
  {
    id: 6,
    nome: "Quadro Decorativo",
    preco: "R$ 150,00",
    avaliacao: 4.9,
    foto: "../assets/produtos/quadro.jpg",
    vendedor: "Leandra",
    categoria: "Jardim e Decoração",
    vendas: 1,
    avaliacaoUsuario: "O quadro é simplesmente maravilhoso! As cores são vibrantes, e o acabamento é perfeito. Superou minhas expectativas.",
  },
  {
    id: 7,
    nome: "Almofada Artesanal",
    preco: "R$ 35,00",
    avaliacao: 4.3,
    foto: "../assets/produtos/almofada.jpg",
    vendedor: "Mariana",
    categoria: "Quarto",
    vendas: 1,
    avaliacaoUsuario: "A almofada é bem bonita e confortável, mas a cor não era exatamente como eu esperava. Ainda assim, é um bom produto.",
  },
  {
    id: 8,
    nome: "Cobertor de Lã",
    preco: "R$ 90,00",
    avaliacao: 4.4,
    foto: "../assets/produtos/cobertor.jpg",
    vendedor: "Roberta",
    categoria: "Quarto",
    vendas: 1,
    avaliacaoUsuario: "Cobertor muito aconchegante e quente, ideal para o inverno. O único ponto negativo é que ele soltou um pouco de fiapos nas primeiras lavagens.",
  },
  {
    id: 9,
    nome: "Porta Sabonete",
    preco: "R$ 20,00",
    avaliacao: 4.2,
    foto: "../assets/produtos/porta_sabonete.jpg",
    vendedor: "Elisa",
    categoria: "Banho",
    vendas: 1,
    avaliacaoUsuario: "Funciona bem e tem um design simples, mas o material poderia ser um pouco mais resistente. No geral, cumpre o que promete.",
  },
  {
    id: 10,
    nome: "Fruteira de Madeira",
    preco: "R$ 100,00",
    avaliacao: 4.6,
    foto: "../assets/produtos/fruteira.jpg",
    vendedor: "Rafaela",
    categoria: "Cozinha",
    vendas: 1,
    avaliacaoUsuario: "Fruteira muito bem feita e resistente. O design é bonito e prático. Só achei um pouco cara pelo tamanho.",
  },
  {
    id: 11,
    nome: "Jardineira Suspensa",
    preco: "R$ 120,00",
    avaliacao: 4.8,
    foto: "../assets/produtos/jardineira.jpg",
    vendedor: "Bianca",
    categoria: "Jardim e Decoração",
    vendas: 1,
    avaliacaoUsuario: "Ótima jardineira! Fácil de instalar e muito resistente. As plantas ficaram lindas nela. Recomendo!",
  },
  {
    id: 12,
    nome: "Espelho Decorativo",
    preco: "R$ 75,00",
    avaliacao: 4.7,
    foto: "../assets/produtos/espelho.jpg",
    vendedor: "Juliana",
    categoria: "Jardim e Decoração",
    vendas: 1,
    avaliacaoUsuario: "Espelho muito bonito e de boa qualidade. Apenas tive que trocar a moldura porque veio com um pequeno defeito, mas o atendimento foi excelente.",
  },
];
